### ISSUE TITLE
Trying to use Pronto Fuel with Docker on Ubuntu 22.04

### ISSUE THREAD

**Issue by well-prado** [prontostack/pronto-fuel#2]
Estou tentando utilizar o Pronto Fuel, clono o repositório (que usando o comando que está no README.MD dá erro por não ter permissão), depois disso abro o VS Code e clico em "Reopen in Container" e então uma nova janela se abre e ele começa a instalar as dependências. No entanto, em determinado ponto retorna este erro:

[remoteContainers-2022-05-02T19-39-06.917Z.log](https://github.com/prontostack/pronto-fuel/files/8605665/remoteContainers-2022-05-02T19-39-06.917Z.log)

Tenho NVM e todo o ambiente instalado, até instalei na minha máquina o PHP CLI, no entanto como é uma imagem Docker entendo que não precisaria necessariamente ter isso instalado na minha máquina.

Poderiam me ajudar?

Ubuntu 22.04 LTS
nvm: 0.39.1
npm: 8.6.0
PHP 8.1.5 (cli)
Docker version 20.10.14, build a224086
Visual Studio Code: 1.66.2
Remote-Containers Extension: v0.231.6

**Comment by ErasmoDev** [comment]
Também estou tendo esse erro ao usar o devContainer (tenho docker composer e php no windows também), mas ao tentar sem ser pelo devContainer, ele builda mas não dá os endereços do servidro, ficando assim:

> start
> npm run dev


> dev
> vite --host 0.0.0.0

Pre-bundling dependencies:
  vue
  @inertiajs/inertia-vue3
  axios
  @kyvg/vue3-notification
  @inertiajs/inertia
(this will be run only when your dependencies or config have changed)

  vite v2.7.13 dev server running at:

  ready in 535ms.

**Comment by MtDalPizzol** [comment]
Fala, amigo. Pergunta besta da minha parte, mas só pra confirmar: Você clonou o **Pronto Fuel** ou o **Pronto Admin**? Nos logs vi que a sua pasta chama `pronto-admin`. O Pronto Admin é um projeto abandonado no momento. Então confirme que clonou o **Pronto Fuel**.

O erro de permissão que você mencionou provavelmente é em função de você não ter configurado uma chave SSH na sua conta do GH. Mas você pode clonar por HTTPS: `git clone https://github.com/prontostack/pronto-fuel.git`.

Sobre o erro no build, você teve uma série de erros "E: Couldn't find any package by" na hora de instalar as extensões do PHP. Difícil dizer o que pode estar causando isso, mas eu arriscaria dizer que pode ter sido uma instabilidade no repositório que serve esses pacotes. Pode tentar novamente?

Já passei por casos de ficar um dia inteiro procurando por erros nas minhas configs das imagens e no docker pra no dia seguinte descobrir que era algum repositório que estava fora do ar temporariamente.

**Comment by ErasmoDev** [comment]
No meu caso, eu clonei o pronto-fuel, se analizar, é o mesmo erro que a issue que está fechada estava tendo também, tem 2 dias que sempre clono de novo e tento, mas não vai nas duas formas que está descrito no README. pelo devcontainer e nem pelo npm start, não aparece os servidores pelo npm start T_T

**Comment by MtDalPizzol** [comment]
Fala, @ErasmoDev . Deixem eu tentar entender pra ver se conseguimos resolver: pelo que entendi são 2 cenários de erro:

1. O build **do container do docker** ao tentar abrir o devcontainer no VSCode.
2. O build **do DevServer do Vite** Ao tentar levantá-lo com `npm start` **FORA** do devcontainer.

Procede?

O caso 1 é mais complicado.

O caso 2 você pode tentar remover o `--host 0.0.0.0` do comando `dev` no `package.json`.

**Comment by ErasmoDev** [comment]
@MtDalPizzol retirando o `--host 0.0.0.0` ele subiu o local network.
`vite v2.7.13 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 339ms.
`

Como pede para expor o Network com --host, tentei colocar 127.0.0.1, localhost direto, (com http:// e sem) mas não foi, sem o --host, ele levantou o Local server pelo menos T_T

**Comment by MtDalPizzol** [comment]
Certo... o `--host=0.0.0.0` é específico para rodar dentro do container. Vou bolar algo pra isso ser opcional.

**Comment by ErasmoDev** [comment]
Opa, no aguardo de um fix. Irei usar pelo wsl apenas, sem ser pelo devcontainer. já que tenho tudo que preciso instalado por ele. Quero desinstalar o docker-desktop. Se bem que testei o devContainer usando o docker do wsl (desktop fechado), deu o mesmo erro, isso significa que não preciso do docker-desktop, o devcontainer/vscode reconhece o docker no wsl.

**Comment by well-prado** [comment]
> Fala, amigo. Pergunta besta da minha parte, mas só pra confirmar: Você clonou o **Pronto Fuel** ou o **Pronto Admin**? Nos logs vi que a sua pasta chama `pronto-admin`. O Pronto Admin é um projeto abandonado no momento. Então confirme que clonou o **Pronto Fuel**.
> 
> O erro de permissão que você mencionou provavelmente é em função de você não ter configurado uma chave SSH na sua conta do GH. Mas você pode clonar por HTTPS: `git clone https://github.com/prontostack/pronto-fuel.git`.
> 
> Sobre o erro no build, você teve uma série de erros "E: Couldn't find any package by" na hora de instalar as extensões do PHP. Difícil dizer o que pode estar causando isso, mas eu arriscaria dizer que pode ter sido uma instabilidade no repositório que serve esses pacotes. Pode tentar novamente?
> 
> Já passei por casos de ficar um dia inteiro procurando por erros nas minhas configs das imagens e no docker pra no dia seguinte descobrir que era algum repositório que estava fora do ar temporariamente.

Fala @MtDalPizzol, beleza? Isso nessa tentativa eu estava pegando o pronto-admin, e os mesmos erros acontenciam. Mas a maior parte das tentativas foi no pronto-fuel mesmo. Fazendo uma nova tentativa agora de manhã, os mesmos erros retornam, e o que mais me preocupa é esse:

```
Running hooks in /etc/ca-certificates/update.d...
done.
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.gzDLUatvIy/gpg.1.sh --homedir /root/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C
gpg: key 4F4EA0AAE5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.aw7FcXsMZJ/gpg.1.sh --homedir /root/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C300EE8C
gpg: key 00A6F0A3C300EE8C: public key "Launchpad Stable" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

Sabe me dizer se esses repositórios funcionam perfeitamente pra vc? Não sei se é possível vc tentar usar o WSL 2 baixando o Ubuntu 22.04? É que como não uso Windows, não faço ideia se a Microsoft já liberou essa versão na Windows Store.

Obrigado.

**Comment by MtDalPizzol** [comment]
Então, @well-prado . Eu só uso Windows por causa do WSL. Uso o WSL 2 no Windows 11 com Ubuntu 22.04. Eu estou em viagem e sem tempo para analisar isso com calma. Mas meu palpite é que talvez sejam Dockerfiles desatualizados. Seria o caso de construir novos Dockerfiles com base no Sail (foi isso que fiz quando criei o repo). Talvez algo tenha mudado e os Dockerfiels que estão no repo estejam desatualizados e pra mim esteja funcionando em função de algum cache.

**Comment by MtDalPizzol** [comment]
Semana que vem posso olhar isso com calma e vou postando aqui. Se vocês puderem dar uma força testando, agradeço.

**Comment by well-prado** [comment]
Claro, vou usar um Windows 10 que tenho aqui no Gnome Boxes e vou testar por lá também. Não manjo muito de PHP pra ser sincero, hoje trabalho como Front-End com Vue 2 e eu estava procurando uma solução para trabalhar em um projeto pessoal no estilo monolito mesmo, foi assim que achei os seus vídeos e curti muito o seu conteúdo. Agradeço muito pela atenção. E espero poder ajudar na comunidade assim que ganhar conhecimento e construir uma aplicação própria rsrsrs. Abraços.

**Comment by MtDalPizzol** [comment]
Fala, turma! Pelos menos uns 4 devs apontaram que o build do devcontainer do VSCode no Pronto Fuel não estava funcionando. 

Acredito que o problema era causado por chaves de repositórios do Linux que foram modificadas e não eram mais validas.

Atualizei o Dockerfile que vem no Pronto Fuel e creio que agora deve estar tudo em ordem novamente.

Se alguém se deparar com esse problema novamente e não quiser esperar por mim para resolver a situação, basta dar uma conferida no Dockerfile do Laravel Sail (https://github.com/laravel/sail/blob/1.x/runtimes/8.1/Dockerfile) e compará-lo com o Dockerfile do Pronto Fuel usando alguma ferramenta de diff.

Quem puder confirmar se está funcionando, agradeço!

https://github.com/prontostack/pronto-fuel/commit/95e61a86c99947f4377839aebda6ae8f7a617872

**Comment by jeffersongrassine** [comment]
Por aqui ainda com erro!
(https://user-images.githubusercontent.com/76718247/168845119-f09e1023-376b-40b7-8345-feddce5b8146.png)

**Comment by MtDalPizzol** [comment]
### Rebuild Without Cache

Pessoal. Estou com muita dificuldade de debugar isso. Quem aí puder testar, lembrem de tentar usar um "Rebuild Without Cache", pra tentar construir as imagens do zero.

**Comment by ErasmoDev** [comment]
@MtDalPizzol  Depois da ultima atualização, não tive problemas, fiz 2 testes ontem, deletando as imagens e volumes do docker, depois refazendo de novo. Hoje fiz + 3 testes e funcionou de acordo com o esperado. Sem problemas nenhum usando o DevContainer, Não cheguei a testar sem ser pelo DevContainer pq refiz minha imagem no wsl(está com somente o docker agora), pq começar a usar apenas o DevContainer.
ps: Não estou usando o docker-desktop, apenas o instalado no wsl, não sei se influencia.

**Comment by MtDalPizzol** [comment]
Maravilha, @ErasmoDev ! Muito obrigado pelo feedback!

Para quem quiser usar sem o dev container eu adicionei um script separado no package.json sem o host do Docker e já adicionei essa info no README. Imagino que não terão problemas.

**Comment by giancarlozucoloto** [comment]
Boa noite amigos ,  deletei os container no Docker Desktop 
clonei novamente agora e o erro novamente

![erro 23](https://user-images.githubusercontent.com/40126449/169419158-cd0ca2ef-de38-4c30-baf9-dc3d2dfe3caf.png)

**Comment by giancarlozucoloto** [comment]
![image](https://user-images.githubusercontent.com/40126449/169420489-4ccc2d73-6427-4536-9abe-c96bdd9d5cc3.png)

**Comment by MtDalPizzol** [comment]
@giancarlozucoloto Você usou o Rebuild Without Cache da paleta do VSCode?

**Comment by giancarlozucoloto** [comment]
Bom dia,
 Rebuild Without Cache da paleta do VSCode?
Sim também fiz

**Comment by MtDalPizzol** [comment]
@giancarlozucoloto , @well-prado e @jeffersongrassine O VSCode de vocês está atualizado?

**Comment by giancarlozucoloto** [comment]
April 2022 (version 1.67)
Update 1.67.1: The update addresses this security [issue](https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22April+2022+Recovery+1%22+is%3Aclosed).

Update 1.67.2: The update addresses these [issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22April+2022+Recovery+2%22+is%3Aclosed).

**Comment by jeffersongrassine** [comment]
@MtDalPizzol, atualizei e funcionou por aqui.
Obrigado

**Comment by fabricio-gwadera** [comment]
Fiz o pull do repositório e tentei inicializar diretamente no DevContainer do VSCode, sem alterar qualquer informação, e ainda assim não está dando certo.
Tentei também inicializar sem o cache e também se resultado.
`[2022-10-28T21:03:44.157Z] Creating premia_laravel.test_1 ...
[2022-10-28T21:03:44.742Z] 
Creating premia_laravel.test_1 ... done
[2022-10-28T21:03:44.746Z] Stop (362647 ms): Run: docker events --format {{json .}} --filter event=start
[2022-10-28T21:03:44.929Z] Stop (2178 ms): Run: docker-compose --project-name premia -f d:\htdocs\premia\docker-compose.yml -f c:\Users\f_gwa\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1666990666686.yml -f c:\Users\f_gwa\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1666991022750.yml up -d
[2022-10-28T21:03:44.929Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=premia --filter label=com.docker.compose.service=laravel.test
[2022-10-28T21:03:45.103Z] Stop (174 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=premia --filter label=com.docker.compose.service=laravel.test
[2022-10-28T21:03:45.104Z] Start: Run: docker inspect --type container 3abd1ed6147f
[2022-10-28T21:03:45.275Z] Stop (171 ms): Run: docker inspect --type container 3abd1ed6147f
[2022-10-28T21:03:45.276Z] Start: Inspecting container
[2022-10-28T21:03:45.276Z] Start: Run: docker inspect --type container 3abd1ed6147f1424a8ce1c948ca36bd9f53fb376c295b5a66cd6f4cf54bbc81f
[2022-10-28T21:03:45.462Z] Stop (186 ms): Run: docker inspect --type container 3abd1ed6147f1424a8ce1c948ca36bd9f53fb376c295b5a66cd6f4cf54bbc81f
[2022-10-28T21:03:45.462Z] Stop (186 ms): Inspecting container
[2022-10-28T21:03:45.463Z] Start: Run in container: /bin/sh
[2022-10-28T21:03:45.492Z] Start: Run in container: uname -m
[2022-10-28T21:03:45.643Z] Stop (180 ms): Run in container: /bin/sh
[2022-10-28T21:03:45.643Z] Shell server terminated (code: 1, signal: null)
[2022-10-28T21:03:45.643Z] Error response from daemon: Container 3abd1ed6147f1424a8ce1c948ca36bd9f53fb376c295b5a66cd6f4cf54bbc81f is not running
[2022-10-28T21:03:45.643Z] Start: Run in container: cat /etc/passwd
[2022-10-28T21:03:45.643Z] Stdin closed!
[2022-10-28T21:03:45.644Z] Error: An error occurred setting up the container.
[2022-10-28T21:03:45.644Z]     at _se (c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1812:2820)
[2022-10-28T21:03:45.644Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-28T21:03:45.644Z]     at async Xse (c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1874:2203)
[2022-10-28T21:03:45.645Z]     at async Uf (c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1874:3193)
[2022-10-28T21:03:45.645Z]     at async Cae (c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:10350)
[2022-10-28T21:03:45.645Z]     at async yae (c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:10104)
[2022-10-28T21:03:45.662Z] Stop (366250 ms): Run: C:\Users\f_gwa\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\f_gwa\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\htdocs\premia --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\htdocs\premia --log-level debug --log-format json --config d:\htdocs\premia\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-28T21:03:45.662Z] Exit code 1
[2022-10-28T21:03:45.666Z] Command failed: C:\Users\f_gwa\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\f_gwa\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\f_gwa\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\htdocs\premia --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\htdocs\premia --log-level debug --log-format json --config d:\htdocs\premia\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-28T21:03:45.666Z] Exit code 1`

**Comment by fabricio-gwadera** [comment]
A versão [0.0.2](https://github.com/prontostack/pronto-fuel/releases/tag/0.0.2) funcionou corretamente no dev container

**Comment by welsontec** [comment]
Conseguiu resolver @giancarlozucoloto ?
Estou com este mesmo problema, já atualizado o VSCode (1.75.1), o Docker Desktop (4.16.3), o Dev Container (0.275.1);
Testei clonando o Pronto Fuel atual original, com atualização do Dockerfile do Laravel Sail e com as versões 0.0.2 e 0.1.0 via download;

meu erro atual é igual:
![image](https://user-images.githubusercontent.com/111821086/218280405-d42fd582-2cf1-493c-a456-05e99fe2aeee.png)

**Comment by welsontec** [comment]
> Conseguiu resolver @giancarlozucoloto ? Estou com este mesmo problema, já atualizado o VSCode (1.75.1), o Docker Desktop (4.16.3), o Dev Container (0.275.1); Testei clonando o Pronto Fuel atual original, com atualização do Dockerfile do Laravel Sail e com as versões 0.0.2 e 0.1.0 via download;
> 
> meu erro atual é igual: ![image](https://user-images.githubusercontent.com/111821086/218280405-d42fd582-2cf1-493c-a456-05e99fe2aeee.png)

erro burro, troquei o end line de CRLF para LF

**Comment by MtDalPizzol** [comment]
Pessoal. Esse tipo de falha no build pode ocorrer por N motivos, inclusive, muito provavelemnte, por atualizações em códigos que não estão no projeto (pacotes do linux que a imagem do docker vai instalar, por exemplo). Os prints e logs acima são todos casos diferentes.

Nesse último do @YuriMarcio , parece um erro relacionado a execução de algum comando do Node/NPM, mas o erro que está causando a falha do build não está nesse log. @YuriMarcio , se você puder colar o log aqui ou dar um print um pouco mais acima onde mostre o erro do Node, talvez dê para entender o que está acontecendo.

Ademais, pessoal, notem que este projeto está desatualizado. Não tive tempo de mantê-lo. **Isso não quer dizer que ele esteja inutilizável.** Atualizando alguns pacotes, esse repo ainda deve servir para projetos de longo prazo sem problemas. Eu só ainda não tenho certeza de que continuarei utilizando-o como base para os meus projetos futuros pois estou avaliando 2 alternativas ao Inertia que são o Splade e LW3.

Ambos tem seus prós e contras e eu ainda estou avaliando. De qualquer forma, esse projeto ainda é um bom fallback para quem ainda prefere trabalhar num paradigma mais tradicional com Vue e Inertia. Caso eu decida não migrar para uma das alternativas, voltarei a manter esse repo mais ativamente.
